user_bundle:
    resource: "@securityUserBundle/Resources/config/routing.yml"
    prefix:   /


#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

#user_bundle:
#   resource: "@tutoUserBundle/Resources/config/routing.yml"